import {
  Ambulance,
  Baby,
  BabyCarriage,
  Bed,
  Bone,
  BowlFood,
  Carrot,
  Coffee,
  Drop,
  DropHalfBottom,
  Ear,
  Eye,
  Flask,
  Funnel,
  Hand,
  HandHeart,
  Heart,
  Heartbeat,
  ListMagnifyingGlass,
  PersonSimpleRun,
  Pill,
  Scan,
  Scissors,
  Sparkle,
  Stethoscope,
  Syringe,
  Tooth,
  Truck,
  UserList,
  Wind,
} from '@phosphor-icons/react/dist/ssr'

export const DEPARTMENT_ICON_MAP = {
  'general-surgery': Scissors,
  orthopedics: Bone,
  urology: Drop,
  ophthalmology: Eye,
  'ent-ear-nose-throat': Ear,
  dentistry: Tooth,
  'plastic-reconstructive-surgery': Hand,
  'general-medicine': Stethoscope,
  cardiology: Heartbeat,
  pulmonology: Wind,
  nephrology: Funnel,
  gastroenterology: BowlFood,
  endocrinology: Flask,
  dermatology: Sparkle,
  'gynaecology-obstetrics': Baby,
  'pediatrics-neonatology': BabyCarriage,
  'dietetics-nutrition': Carrot,
  'physiotherapy-rehabilitation': PersonSimpleRun,
} as const

export const SERVICE_ICON_MAP = {
  ipd: Bed,
  opd: UserList,
  icu: Heartbeat,
  emergency: Ambulance,
  'ot-complex': Scissors,
  nursing: HandHeart,
  anesthesia: Syringe,
  ambulance: Truck,
  dialysis: Funnel,
  pharmacy: Pill,
  'blood-bank': DropHalfBottom,
  cafeteria: Coffee,
  pathology: Flask,
  radiology: Scan,
  'cardiac-diagnostics': Heart,
  'lab-tests': ListMagnifyingGlass,
} as const

export type DepartmentIconSlug = keyof typeof DEPARTMENT_ICON_MAP
export type ServiceIconSlug = keyof typeof SERVICE_ICON_MAP
